### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/ssl/PKCS8Key

### ISSUE THREAD

**Issue by javikin** [bigdata-mx/factura-electronica#107]
Hola estoy implementando la nueva version del KeyLoader, ya que ahora para obtener la key el certificado se necesita de KeyLoaderFactory. ya hice los cambios pero me arroja el siguiente error, sin embargo si cuento con la libreria.

<dependency>
        <groupId>commons-logging</groupId>
        <artifactId>commons-logging</artifactId>
        <version>1.1.1</version>
</dependency>

Error: 

SEVERE:   >>java.lang.NoClassDefFoundError: org/apache/commons/ssl/PKCS8Key

> >  at mx.bigdata.sat.security.PrivateKeyLoader.extractProtectedPrivateKey(PrivateKeyLoader.java:89)
> >  at mx.bigdata.sat.security.PrivateKeyLoader.setPrivateKey(PrivateKeyLoader.java:67)
> >  at mx.bigdata.sat.security.PrivateKeyLoader.<init>(PrivateKeyLoader.java:34)
> >  at mx.bigdata.sat.security.factory.KeyLoaderFactory.createInstance(KeyLoaderFactory.java:35)

Alguien tuvo el mismo problema?

**Comment by Ivantmtest** [comment]
Lograste la solución amigo?

**Comment by javikin** [comment]
La vdd no recuerdo, pero creo que esta librería ya no tiene soporte y recomiendan mejor usar https://github.com/GrupoCorasa/factura-electronica
