### ISSUE TITLE
Nuevo en esto

### ISSUE THREAD

**Issue by jakoujan** [bigdata-mx/factura-electronica#122]
Hola Amigos soy nuevo y estoy tratando de implementar esta libreria en un sistema hecho a medida, lo que no tengo conocimiento es a cerca de los PAC's o cual es el proceso inicial ya que no comprendo como es el proceso de timbrado del CFDI y si se genera o como se guarda en su caso?

Gracias por su apoyo.

**Comment by charliefes** [comment]
Hola, igual tenemos una app y no queda muy claro el proceso del tema del timbrado. Veo que los PAC's ofrecen por lo general Web Services para timbrar. Se debe mandar a llamar esos WS del PAC dentro de ésta implementación ó dentro de ésta implementación se puede hacer el timbrado directamente, entonces necesito un ¿PAC? o ya no, o ¿que necesitaría del PAC?

**Comment by mauriciobaeza** [comment]
El PAC es, por ahora, indispensable... por ahora, nadie nos espacamos de alguno. En general, hay dos formas con los PACs...

1.- Enviar el CFDI ya sellado, te lo regresa timbrado
2.- Enviar el CFDI ya sellado, te regresa solo el timbre, tu tienes que agregarlo al CFDI

Saludos
