### ISSUE TITLE
mx.bigdata.sat.cfdi.v32  no existe

### ISSUE THREAD

**Issue by reyesazael12** [bigdata-mx/factura-electronica#130]
Saludos acabo de descargar el codigo quiero compilar pero me indica que el paquete mx.bigdata.sat.cfdi.v32 no existe y fisicamente lo comprobe, incluso en la pagina principal no aparecen. 
Alguien me puede apoyar, gracias de antemano.

**Comment by reyesazael12** [comment]
El paquete mx.bigdata.sat.cfdi.schema tampoco existe.
Lo que pasa es que me gustaria contribuir con el proyecto estoy intentando comprender el codigo pero como esta incompleto no havanzo mucho.

**Comment by elmer-garduno** [comment]
Hola, el código que no está se genera automáticamente corriendo uno de los
objetivos de maven, en la ayuda hay instrucciones de como generarlo en
eclipse y NetBeans. Dime si esta información es suficiente

**Comment by reyesazael12** [comment]
Trate de Seguir los pasos que indicas, pero uso Netbeans 8.1, tuve que indicar la version para varias dependencias dentro el archivo pom con eso logre generar las clases que faltaban, sin embargo, marca el siguiente error

COMPILATION ERROR : 
-------------------------------------------------------------
mx/bigdata/sat/security/PrivateKeyLoader.java:[22,8] mx.bigdata.sat.security.PrivateKeyLoader is not abstract and does not override abstract method <T>getKey() in mx.bigdata.sat.security.KeyLoader
mx/bigdata/sat/security/PublicKeyLoader.java:[18,8] mx.bigdata.sat.security.PublicKeyLoader is not abstract and does not override abstract method <T>getKey() in mx.bigdata.sat.security.KeyLoader
2 errors 
Entiendo que error deveria de corregirse con:
    @Getter
    PrivateKey key;

Alguna sugerencia?
