### ISSUE TITLE
timbrado

### ISSUE THREAD

**Issue by mishmario** [bigdata-mx/factura-electronica#138]
Hola compañeros, soy nuevo en este tema del cfdi, y he checado las librerias que se han desarrollado entorno a las facturas electronicas, la pregunta que tengo es, si  puedo timbrar con estas librerias mis facturas sin contratar el servicio de algun pac.

Muchas gracias de antemano

**Comment by mauriciobaeza** [comment]
No... cualquier librería requiere un PAC...

No se como, pero deberíamos obligar al SAT a que nos de acceso a su timbrado gratuito por webservice...

**Comment by Erilas** [comment]
Ya lo intente por medio de mi trabajo (institución de gobierno) y ni por
qué tenemos convenios nos quisieron dar algún tipo de web service de
timbrado

Saludos!

**Comment by mauriciobaeza** [comment]
Pues vamos organizándonos... nos obligan a hacer una gran inversión para esto, todos los servicios y su sueldos salen de nuestros impuestos y todavía tenemos que pagar...

¿Quien se apunta?

**Comment by mishmario** [comment]
Se agradecen los comentarios compañeros que son muy alentadores, en mi opinión creo que SAT debería de ofrecer los servicios del PAC sin intermediarios, pero tengo otra pregunta y ojalá que no suene muy trivial, supongamos que ya tenemos nuestra factura.xml sellado y verificado por las librerías de java, luego se lo envio al PAC (¿por correo, algún API?), ¿puedo recibir los sellos del PAC de inmediato y seguir generando mi factura final?, o tengo que decirle al cliente que regrese al otro día por su factura?.

Gracias de antemano compañeros.

**Comment by Erilas** [comment]
Hola
De hecho el servicio del pac debe ser inmediato (si no mejor busca uno que
si lo sea), el pac que tengo me regresa todo, incluso por separado (XML con
folio fiscal, el folio fiscal por separado y el sello del pac por separado).
Las preguntas no son triviales amigo, lamentablemente el SAT casi no da
información de algunos procesos, y aveces los pac sólo te lo ponen de modo
"hacemos todo lo que necesita el SAT" pero ni siquiera te comentan cual es
el proceso completo.

Saludos!

**Comment by mishmario** [comment]
Estimados compañeros del viaje, acabo de implementar las librerías de java para generar el CFDI, ahora necesito el servicio de algún PAC que me facilite una librería en java para que me genere el timbrado, ahora que ya puedo r sellar mis archivos XML, de casualidad ¿alguien conoce un PAC que me permita trabajar en modo DEMO para probar enviando mis archivos XML?, espero que comprendas mis novatadas, pero se los agradecería infinitamente su colaboración..

gracias, Buenas noches a todos.
