### ISSUE TITLE
leer timbreFiscal a partir de un XML timbrado

### ISSUE THREAD

**Issue by mishmario** [bigdata-mx/factura-electronica#139]
hola buenas noches, mi pregunta es lo siguiente, tengo un archivo XML sellado y timbrado, y quiero generar un comprobante a partir de este archivo, lo que no sé es como leer los valores del TimbreFiscalDigital (sello del Sat, sello  del CSD....), espero que me haya explicado bien..

saludos.

**Comment by jjjimenez** [comment]
Hola,
Yo hago lo siguiente
    private void loadComplementos(Comprobante comprobante) {
        List<Object>complementos = comprobante.getComplemento().getAny();
        if( complementos!=null  ) {
            Object complemento;
            for(int index=0; index<complementos.size(); index++) {
                complemento = complementos.get(index);
                Logger.debug(this,"Complemento["+(index+1)+"] "+complemento);
                if( complemento instanceof TimbreFiscalDigital ) {
                    timbreFiscal = (TimbreFiscalDigital)complemento;
                    setCadenaOriginalCertificacion( makeCadenaOriginal(timbreFiscal) );
                } else if( complemento instanceof Nomina ) {
                    complementoNomina = (Nomina) complemento;                } else if ... 

                } else {
                    Logger.warn(this, "complemento NO SOPORTADO!");
                }
            }    //    for
        }    //    if
        
    }    //    loadComplementos

Si hay alguna manera mas optima por favor diganme!
 ---Jaime Joel Jiménez Sánchez jjjimenez@yahoo.com
+52 (871) 690 3232

**Comment by mishmario** [comment]
Estuve probando la solución que proporcionas gentilmente mi estimado **jjjimenez**, y dejame decirte que me acabas de salvar la vida, me ha funcionado el código de maravilla, ahora ya puedo extraer los valores de TimbreFiscalDigital.

Te agradezco por tu respuesta.
Buenas noches.
