### ISSUE TITLE
incluir el concepto de recibo de nomina

### ISSUE THREAD

**Issue by antonioalvarezm** [bigdata-mx/factura-electronica#140]
Quiero colaborar con el concepto de recibo de nomina, ya he descargado el código fuente y falta el paquete mx.bigdata.sat.cfdi.v32.schema. Serían gentiles de agregarlo por favor.

**Comment by hortegag91** [comment]
El XSD está incluido en la librería y se genera de manera correcta. Debes tener un error a la hora de compilar que no te está creando dichas paqueterías. Éstas las debería crear dentro de Generated Sources
