### ISSUE TITLE
Complemento de servicios parciales de construccion

### ISSUE THREAD

**Issue by hugo-haro** [bigdata-mx/factura-electronica#149]
Hola, soy nuevo en esto.
Alguien sabe como puedo incluir el complemento 
http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Paginas/complemento_servicios_parciales_construccion.aspx

@hortegag91 tenias algo de ese complemento, podrías compartirme algo de información.

Saludos

**Comment by camarillo** [comment]
@hugo-haro en el Issues #120 indican como agregar los complementos con los XSD

**Comment by hugo-haro** [comment]
Muchas gracias @camarillo con tu ayuda logre agregar el complemento.

**Comment by camarillo** [comment]
@hugo-haro por nada, seria bueno que subieras el cambio para que estuviera en la librería.
