### ISSUE TITLE
Implementar cancelación de CFDI

### ISSUE THREAD

**Issue by elmer-garduno** [bigdata-mx/factura-electronica#16]
_Original author: bigdata.mx (November 25, 2010 14:14:25)_

Existe este documento en el ftp del SAT,  ftp://ftp2.sat.gob.mx/asistencia_ftp/publicaciones/cfdi/Manual%20Operacion%20-%20Cliente%20CFDI%20Interfaces.docx

Ahí está publicado un web service de prueba: https://pruebacfdi.cloudapp.net/Cancelacion/CancelaCFDService.svc

Y viene incluido un WSDL del servicio.

_Original issue: http://code.google.com/p/factura-electronica/issues/detail?id=16_

**Comment by spawnbart** [comment]
Alguien ya pudo consumir correctamente el servicio de cancelación del SAT? https://cancelacion.facturaelectronica.sat.gob.mx/Cancelacion/CancelaCFDService.svc
