### ISSUE TITLE
NotAfter: Sun May 07 09:01:29 PDT 2017

### ISSUE THREAD

**Issue by azaeldevel** [bigdata-mx/factura-electronica#161]
Buen dia

Hoy parece que se vencieron los certificados de pruebas, como puedo obtener nuevos?

  testSign(mx.bigdata.sat.cfd.CFDv22Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testValidateVerify(mx.bigdata.sat.cfd.CFDv22Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testValidateVerifyPrevious(mx.bigdata.sat.cfd.CFDv22Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testValidateVerifyWithFile(mx.bigdata.sat.cfd.CFDv22Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testSellarComprobante(mx.bigdata.sat.cfd.CFDv22Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testSign(mx.bigdata.sat.cfd.CFDv2Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testValidateVerify(mx.bigdata.sat.cfd.CFDv2Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testValidateVerifyWithFile(mx.bigdata.sat.cfd.CFDv2Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testSellarComprobante(mx.bigdata.sat.cfd.CFDv2Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testValidateVerifyPrevoious(mx.bigdata.sat.cfd.CFDv2Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testSign(mx.bigdata.sat.cfdi.CFDv32Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  testValidateVerify(mx.bigdata.sat.cfdi.CFDv32Test): NotAfter: Sun May 07 09:01:29 PDT 2017
  ...
  ...
  ...

**Comment by hortegag91** [comment]
Al menos ayer revisé y no habia nuevos oficiales en el SAT, yo lo que hice de momento para continuar el desarrollo de 3.3 fue poner un IF a la hora de validar ese número de certificado, quedaría algo asi:
`
        String nc = new String(cert.getSerialNumber().toByteArray());
        if (!nc.equals("20001000000200001428")) {
            cert.checkValidity();
        }`

**Comment by ingtemix** [comment]
Dejame ver si puedo conseguirles unos de prueba.

Saludos!!!

**Comment by hortegag91** [comment]
Cerraré este tema debido a que oficialmente no hay nuevo certificados.
He actualizado a la versión 33 dentro del branch "version33" ls agradeceré si pudieran ayudarme a probar y cualquier cosa la comentan.
Saludos.

**Comment by ingtemix** [comment]
Chicos les adjunto algunos certificados.

[Cert_Sellos.zip](https://github.com/bigdata-mx/factura-electronica/files/987424/Cert_Sellos.zip)

Contraseña general de los archivos 12345678a

**Comment by hortegag91** [comment]
Wow!.. aun sin ser oficiales creo que es bastante bueno contar con ellos. Muchas gracias @ingtemix

**Comment by ingtemix** [comment]
De nada es un placer contribuir con ustedes

**Comment by azaeldevel** [comment]
Gracias ya me sirvieron ya sigo con mis pruebas

**Comment by ingtemix** [comment]
De nada @reyesazael12  que bueno que te sirvieron cualquier duda avisenme.

Saludos!!!
