### ISSUE TITLE
Error al generar la cadena original

### ISSUE THREAD

**Issue by miguel2309** [bigdata-mx/factura-electronica#166]
Hola, al generar la cadena original de una factura me la crea incompleta, no toma en cuenta los campos de impuestos de un concepto. En la version 3.3

**Comment by hortegag91** [comment]
Me podrías pasar como genera el XML para hacer pruebas?

**Comment by miguel2309** [comment]
Este es el XML que genera, al utilizar el metodo cfd.getCadenaOriginal() me imprime lo siguiente: ||3.3|A|050|2017-06-02T01:35:09|02|30001000000300023708|2973.25|MXN|3448.97|I|PUE|62350|AAA010101AAA|AP RH CONSULTORES|601|TOSM9309297E2|Investigación Farmacéutica SA de CV|G03|01010101|1.0|ACT|Servicio de nomina correspondiente al periodo del Mon Jun 05 10:25:21 CDT 2017 al Sun Jun 11 10:25:21 CDT 2017|2973.25|2973.25|475.72||


[recibo_02-06-2017.txt](https://github.com/bigdata-mx/factura-electronica/files/1052479/recibo_02-06-2017.txt)

**Comment by hortegag91** [comment]
Si estas utilizando el branch: version33?

**Comment by miguel2309** [comment]
Creo que utilice el master, probare con el que me comentas, gracias por la ayuda

**Comment by lezamablr** [comment]
Saludos. Yo uso el branch version33 y no me carga la parte de impuestos del concepto, alguna idea?

**Comment by hortegag91** [comment]
Puedes guardar como se genera el XML y la cadena por favor?

**Comment by lezamablr** [comment]
Esta es la cadena:
||3.3|R|274979|2017-06-07T06:25:35|01|00001000000300350688|3.68|MXN|1|4.27|I|PUE|03510|HER890619SQ4|Herrasa, S.A. de C.V.|601|XAXX010101000|CLIENTE MOSTRADOR|G01|01010101|002-0017|1.00|H87|JGO|10-27 N BRIDA 1' NIQUEL JUEGO 2 PZAS|3.68|3.68|0.00|10 47 3203 0000087|0.59||
Y te anexo el XML.
[1_R-274979.txt](https://github.com/bigdata-mx/factura-electronica/files/1062361/1_R-274979.txt)

**Comment by miguel2309** [comment]
Saludos, si se pudo solucionar este detalle?

**Comment by miguel2309** [comment]
Hola ya uso la version33 y sigue sin cargar la parte de impuestos al generar la cadena original, alguna idea de por que pasa esto?

**Comment by camarillo** [comment]
Puedes subir como se genera tu xml y como le pasas la información a la libreria la información?.

**Comment by miguel2309** [comment]
como paso la informacion?

CFDv33 cfd = new CFDv33(CFDv33Simple.createComprobante(factura,facturaDAO.findPFacturasFactura(factura), numFolio));

factura,  es un objeto que tiene los datos para crear el xml

facturaDAO.findPFacturasFactura(factura) es la lista de conceptos de la factura

CFDv33Simple es igual a ExampleCFDv33Factory solo que en lugar de tener las constantes tiene variables

Cadena Original: ||3.3|A|181|2017-07-31T11:47:16|02|30001000000300023708|2973.25|MXN|3448.97|I|PUE|62350|AAA010101AAA|AP RH CONSULTORES|601|TOSM9309297E2|Investigación Farmacéutica SA de CV|G03|01010101|1.0|ACT|Servicio de nomina correspondiente al periodo del 05-06-17 al 11-06-17|2973.25|2973.25|475.72||

[recibo_31-07-2017.txt](https://github.com/bigdata-mx/factura-electronica/files/1188278/recibo_31-07-2017.txt)

**Comment by miguel2309** [comment]
esa información te sirve? o necesitas saber algo mas? gracias por el apoyo

**Comment by hugo-haro** [comment]
Hola, @miguel2309 pudiste solucionar tu problema con la cadena original. Tengo el mismo problema y me gustaría compartir lo que he echo.

**Comment by ghost** [comment]
Pongan su XML en algún lugar accesible, para mostrarles como debería ser su cadena original de dicho archivo.

**Comment by hugo-haro** [comment]
Gracias @mauriciobaeza te dejo un link para el xml https://1drv.ms/u/s!AtkOeVKCSIVImlbARdl4Jhqme4yu
y esta es la cadena original que se esta generando.
||3.3|F|202|2017-09-06T15:25:03|01|00001000000303489415|CONTADO|1.00|0.00|MXN|1|1.16|I|PUE|36510|ROHH820213BY2|HUGO RODRIGUEZ HARO|621|HECS911101A34|SELENNE ALEJANDRA HERNANDEZ CORONA|MEX|G01|01010101|01010101|1.00|H87|PIEZAS|SOPORTE TECNICO|1.00|1.00|0.00|0.16||

Yo creo que el problema es el archivo cadenaoriginal_3_3.xslt, tengo uno que me proporciono mi pac, pero no se como integrarlo al proyecto.
Saludos y gracias por el apoyo.

**Comment by ghost** [comment]
Tu cadena:

||3.3|F|202|2017-09-06T15:25:03|01|00001000000303489415|CONTADO|1.00|0.00|MXN|1|1.16|I|PUE|36510|ROHH820213BY2|HUGO RODRIGUEZ HARO|621|HECS911101A34|SELENNE ALEJANDRA HERNANDEZ CORONA|MEX|G01|01010101|01010101|1.00|H87|PIEZAS|SOPORTE TECNICO|1.00|1.00|1.00|002|Tasa|0.160000|0.16|0.00|002|Tasa|0.160000|0.16|0.16||

**Comment by hugo-haro** [comment]
Gracias @mauriciobaeza , el problema es que la cadena la genera la librería, pero la genera mal. Yo creo que el problema es el xslt de la cadena original, pero no se en donde modificarlo.

**Comment by ghost** [comment]
¿Te refieres a la librería de este repositorio?... en la rama version33 están los XSLT
https://github.com/bigdata-mx/factura-electronica/tree/version33/src/main/resources/xslt

**Comment by hugo-haro** [comment]
@mauriciobaeza si es la librería de este repositorio, la cadena original es generada en automático al sellar el comprobante y al parecer no se genera en forma adecuada. Cuando mando un xml a timbrar, el pac me devuelve el error de sello mal formado, ya hable con el pac y me comenta que mi cadena original esta mal formada. Saque la cadena original con el método getCadenaOriginal(), la cadena generada es la que te mande y esta incompleta. Quiero realizar una prueba con el xslt que me proporciona mi pac (no se si esto lo solucionara es un intento), pero si lo reemplazo en los resources me marca el siguiente error:

COMPILATION ERROR : 
-------------------------------------------------------------
mx/bigdata/sat/cfdi/CFDv33.java:[250,95] cannot find symbol
  symbol:   method getAny()
  location: interface java.util.List<mx.bigdata.sat.cfdi.v33.schema.Comprobante.Complemento>

Si tu tienes alguna alternativa para este error, te agradecería la compartieras.

Saludos.

**Comment by ghost** [comment]
Lo siento, Java y yo nunca nos entendimos...

viendo el código, aquí: 
https://github.com/bigdata-mx/factura-electronica/blob/version33/src/main/java/mx/bigdata/sat/cfdi/CFDv33.java#L63

Reemplazando esta ruta con "exactamente" el mismo nombre "debería" funcionar. Pero no me hagas caso, no programo en Java y creo que los compañeros dueños del repositorio son los indicados para saber que hacer.

Saludos

**Comment by hugo-haro** [comment]
@mauriciobaeza Lo seguiré intentando, agradezco tu ayuda.

**Comment by hortegag91** [comment]
Ya está disponible la nueva actualización, hay que importar clases distintas en los proyectos donde lo tengamos impementados, pero no debería representar mayor problema. Les agradeceré lo prueben para que bote lo que esté mal

**Comment by hugo-haro** [comment]
@hortegag91 , con los cambios aplicados ya fue posible timbrar, por lo menos con mi pac ya. La cadena original ya se genero correctamente, Agradezco tu ayuda.

**Comment by hortegag91** [comment]
Gracias por avisar, cerraré el issue

**Comment by holajorge** [comment]
hola @hugo-haro  podrias comentar o compartir como solucionaste el error 7 ERROR AL GENERAR SELLO, CADENA ORIGINAL MAL FORMADA, gracias.

**Comment by hortegag91** [comment]
> hola @hugo-haro podrias comentar o compartir como solucionaste el error 7 ERROR AL GENERAR SELLO, CADENA ORIGINAL MAL FORMADA, gracias.

En teoría, utilizando el siguiente repo: https://github.com/GrupoCorasa/factura-electronica debería solucionar el problema.

**Comment by hugo-haro** [comment]
Hola @holajorge buen día, el error que en su momento presento la cadena original fue generado por el xlst proporcionado por el sat, lo reemplace en mi código y con eso funciono. Como lo menciona @hortegag91 con la libreria actual debe andar todo bien.
