### ISSUE TITLE
xmlns y xsi:schemaLocation a nivel de complementos

### ISSUE THREAD

**Issue by novat-xml** [bigdata-mx/factura-electronica#168]
Buen día alguien me podria poyar? estoy tratando de insertar el xmlns y el xsi:schemaLocation a nivel de Complemento, por ejemplo lo que hacen en el complemento timbre fiscal digital, <tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/TimbreFiscalDigital/TimbreFiscalDigital.xsd", estoy usando su aplicación pero no puedo hacer lo que quiero.

Saludos.

**Comment by hortegag91** [comment]
Para los complementos ya viene eso definido en la nueva versión, dentro de la clase CFDiv33, en el método: private String getSchemaLocation()
En la versión anterior a la 3.3 no está contemplado.
