### ISSUE TITLE
Liga desactualizada

### ISSUE THREAD

**Issue by ikyaro2000** [bigdata-mx/factura-electronica#169]
En la página principal en la sección 
Descarga las dependencias esta apuntando hacia:
http://search.maven.org/remotecontent?filepath=mx/bigdata/cfdi/cfdi-base/0.2.5/cfdi-base-0.2.5-bin.zip
se tendrá la liga actualizada a la última versión para la 3.3, yo solo la llamo desde php para sellar.

saludos

**Comment by hortegag91** [comment]
La verdad es que no tengo conocimiento como se suban las actualizaciones al repositorio central, imagino que @elmer-garduno  podrá apoyarnos con actualizar el repo central

**Comment by danielfigueroaj** [comment]
Yo hice checkout del branch de la version 33 y genere el jar localmente, aun no he empezado a hacer mis pruebas de la version 3.3 pero lei que al menos 1 par de usuarios ya lo hicieron y fue exitoso. Estaria bien hacer ya un merge y hacer el release del cfdi-base-0.3.0

**Comment by franciscomontiel** [comment]
Generé el war localmente también y parece funcionar bien, excepto por unos patrones en el XSD.

**Comment by danielfigueroaj** [comment]
Yo espero hoy o mañana comenzar a implementar la version 3.3, actualmente ya tengo en produccion la 3.2, ya les estare compartiendo mis resultados
