### ISSUE TITLE
Autenticidad de codigo frente al SAT

### ISSUE THREAD

**Issue by cala8814** [bigdata-mx/factura-electronica#173]
Buen día:

Estamos empleando su desarrollo de validación de Facturas en uno de nuestros proyectos, pero nos gustaría saber si este desarrollo que nos proporcionan para revisar la autenticidad de la la factura electronica, tiene algún fundamento legal que indique que cumple con las normas del SAT.

**Comment by hortegag91** [comment]
Está basando con los XSDs que liberó el SAT, por lo que en teoría debe cumplir en su totalidad con dicha validación.
Si bien en teoría cumple con la estructura de forma y sintaxis, hasta ahora no se ha implementado la matriz de validaciones, por lo que podría contener errores de información.

**Comment by cala8814** [comment]
Ok, tendrás de casualidad la url donde están los XSDs liberados por el SAT?

gracias por tu pronta respuesta.

**Comment by hortegag91** [comment]
Ahora no los tengo a la mano, pero para buscarlos directamente en el SAT, puedes ponerle "anexo 20" en Google, y la primer liga te llevará a dicho apartado donde puedes encontrar los xsds que el SAT definió, la matriz de validaciones y los xslts (entre otras cosas).

**Comment by hortegag91** [comment]
También puedes encontrarlos dentro del proyecto en la carpeta de XSD dentro de resources

**Comment by camarillo** [comment]
Los puedes encontrar aqui: 
http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Paginas/validacion_comprobantes.aspx

**Comment by cala8814** [comment]
Muchisimas gracias

**Comment by MariaDev12** [comment]
A mi me marca error el PAC porque el sello no esta bien formado, al revisar el valor de la cadena original del cfdi 3.3 y al parecer faltan datos, reemplace el .xslt de la cadena original al proyecto maven y no funciono correctamente que puedo hacer??? :(

**Comment by danielfigueroaj** [comment]
@MariaDev12 checa este issue:

https://github.com/bigdata-mx/factura-electronica/issues/167

**Comment by MariaDev12** [comment]
@danielfigueroaj Muchas gracias :D voy a hacer la correción que mencionan en issue y te digo como me fue  :)

**Comment by danielfigueroaj** [comment]
@MariaDev12  Si, si implementas el fix que puso @aperezc48 no tendras ningun problema ;) Yo asi lo hice y ya seteando bien las propiedades de los objetos ya estoy timbrando.
