### ISSUE TITLE
¿Alguien ha logrado timbrar con FINKOK un cfdiv33?

### ISSUE THREAD

**Issue by acordovar** [bigdata-mx/factura-electronica#176]
Buenas tardes amigos!

Llevo varios días tratando de timbrar con FINKOK y no hay modo que salga.
Sustituí la cadena original de este PAC en el proyecto cfdiv33 local y me da errores en los test al momento de compilar.
Si alguien ya logro timbrar con este PAC por favor que me ayude!.
De antemano, muchas gracias.

Saludos!

Alexie

**Comment by acordovar** [comment]
Olvide decirles que el problema que tengo es que cuando envío el cfdiv33 al PAC, este me devuelve el siguiente código de error:

Codigo Error: CFDI33102
Mensaje de incidencia: El resultado de la digestión debe ser igual al resultado de la desencripción del sello.
Work Process Id: WorkProcessId

Espero sus comentarios!

Alexie

**Comment by ghost** [comment]
Si, nosotros timbramos sin problemas con Finkok. El error es claro, estas sellando mal tus facturas. Tenemos un entorno completamente libre y abierto de pruebas donde puedes verificar por donde anda el problema, no importando que lenguaje uses, mira por aca: https://gitlab.com/mauriciobaeza/cfdi-test

Por favor, cualquier duda con este desarrollo, NO preguntes por aquí, este es otro repositorio, usa el sistema del proyecto: https://gitlab.com/mauriciobaeza/cfdi-test/issues

Saludos

**Comment by acordovar** [comment]
Gracias Mauricio,

Estoy usando la librería, el branch cfdi33.
Según sé, el problema solo nos ha pasado a unos cuantos.
Voy a considerar la herramienta que me recomiendas.

Saludos!

**Comment by camarillo** [comment]
@acordovar puede ser lo que les ha ocurrido a los demas de la cadena original.
