### ISSUE TITLE
PAC alta disponibilidad y carga

### ISSUE THREAD

**Issue by Erilas** [bigdata-mx/factura-electronica#177]
Hola, aprovecho el área para preguntarles que tal les ha ido con su PAC en este cambio a 3.3; mi experiencia con el que estoy usando actualmente es terrible y pensamos cambiar de PAC. Tendrán algunas sugerencias de alguno? Necesitamos un PAC de alta disponibilidad y carga ya que diariamente facturamos al rededor de unas 10 000 facturas.

Saludos!

**Comment by acordovar** [comment]
Hola Erilas!

FINKOK promete lo que necesitas. 
http://www.finkok.com

Saludos!

**Comment by Erilas** [comment]
Lo revisare muchas gracias, solo espero que no sea reventa; me tope con varios PAC que solo re vendían el servicio de otros PAC por medio de un web service propio.
Saludos!

**Comment by ghost** [comment]
Ecodex o Finkok son lo que necesitas... estos dos PACs son los únicos que han puesto a disposición de la comunidad, un entorno libre y abierto para pruebas: https://gitlab.com/mauriciobaeza/cfdi-test

puedes probar completamente los servicios antes de contratar, y las librerías desarrolladas están listas para producción. Si bien todo el código está en Python, es muy fácil trasladarlas a cualquier lenguaje.

Saludos
