### ISSUE TITLE
Error en validación de TasaOCuota '0.080000'

### ISSUE THREAD

**Issue by ea24** [bigdata-mx/factura-electronica#178]
Saludos compañeros, estoy a un paso de mandar a timbrar mi factura (en entorno de prueba de mi PAC) sin embargo, al realizar algunas pruebas con impuestos me encontré con un problema en la validación, le asigné a un producto un IEPS de 8% y al validar me muestra el siguiente error:

> El valor **'0.080000'** no es de faceta válida con respecto a la enumeración '[0.000000, 0.160000, 0.265000, 0.300000, 0.530000, 0.500000, 1.600000, 0.304000, 0.350000, 0.059100, 3.000000, 0.298800]'. Debe ser un valor de la enumeración.

El error es evidente pero no debería el valor 0.080000 estar incluido en el Enum, ¿existe algún problema? Los valores del Enum no contienen todos los valores del catálogo c_TasaOCuota.
Saludos.

**Comment by camarillo** [comment]
Podrías modificar el Enum, pero si lo haces el PAC te lo va a regresar por que aplica las mismas validaciones de la libreria.

**Comment by hortegag91** [comment]
@ea24 el error se debe a que el SAT no registró en su catálogo un 8% (tasa) en el IEPS, definió los siguientes valores fijos:

0.530000
0.500000
1.600000
0.304000
0.250000
0.090000
0.080000
0.070000
0.060000
0.030000
0.000000

O un rango de cuota desde 0 a 43.77

Por lo que al enviar un IEPS al 8% te devolerá error ya que no se encuentra en lo definido por el SAT.

**Comment by hortegag91** [comment]
Según el SAT si está permitido el 8%, de hecho definió los siguientes catálogos:
0.530000
0.500000
1.600000
0.304000
0.250000
0.090000
0.080000
0.070000
0.060000
0.030000
0.000000
Deberías reportar esto a tu PAC ya que SI está definido una tasa IEPS con valor 0.08

**Comment by ea24** [comment]
Pero estoy viendo el catálogo y sí viene, voy a probar a modificar el Enum y veré qué sucede con el PAC en mi ambiente de pruebas.
![c_tasaocuota](https://user-images.githubusercontent.com/28816234/30234331-abf96dd0-94c1-11e7-9230-e8a50747244f.png)

¡Saludos cordiales!

**Comment by ea24** [comment]
@hortegag91 el detalle es que el error en la validación de la librería, aún no se lo mando al PAC, por eso posteo este issue ya que el problema según veo es que falta el elemento en el Enum de la librería, no sé si estoy en lo correcto, de otra manera favor de corregirme.
Saludos.

**Comment by hortegag91** [comment]
La verdad la librería estuvo desactualizada y no tenía los ultimos lineamientos, te agradecería si pudieras hacerle un pull ya que si se le hicieron algunos (muchos) cambios hoy por la tarde (a la misma branch de version33) te agradecería si pudieras hacer el pull y probar de nuevo. Se solucione o no, nos comentas por aquí para dar seguimiento o cerrar el issue porfa

**Comment by ea24** [comment]
@hortegag91 he actualizado el proyecto ya no me da problemas al validar el valor 0.080000 para IEPS. Agradezco mucho el apoyo, si en algo puedo servir estoy más que dispuesto.
Saludos cordiales.
