### ISSUE TITLE
Error al validar el complemento de pago

### ISSUE THREAD

**Issue by camarillo** [bigdata-mx/factura-electronica#180]
Hola

Para validar el complemento de pago, a alguien le ha pasado el siguiente error?.
![error complemento d pago](https://user-images.githubusercontent.com/81843/31129105-3cd25f00-a819-11e7-8f9c-58c6f451f5b2.PNG)

![error complemento de pago](https://user-images.githubusercontent.com/81843/31129739-0c63eb02-a81b-11e7-947c-f7c47340beaf.PNG)

Saludos

**Comment by lezamablr** [comment]
Si, el mismo error.... ya lograste resolverlo?

**Comment by mega82es** [comment]
Buen dia,
Mismo error, para evitar el error de compilacion en las clases generadas modifique el atributo @XmlType  de los archivos CMoneda.java, CMetodoPago.java y CTipoFactor (dentro de generated-sources/xjc29), por ejemplo la linea
@XmlType(name = "c_Moneda", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")

quedando como sigue:
@XmlType(name = "c_Moneda_Pagos", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")

Se que no es correcto modificar los archivos generados, no se como hacer el cambio definitivo. Con eso si genero el XML con el complemento de pagos

Saludos

**Comment by lezamablr** [comment]
@mega82es Me hiciste el día campeón, por el momento ya pude guardar el XML y timbrarlo, ya solo falta ver como solucionarlo en el proyecto.... a seguir picando piedra!

**Comment by camarillo** [comment]
@lezamablr aun no... lo sigo investigando.

**Comment by camarillo** [comment]
@mega82es al mandarlo al pac no te regresa un error?.

Yo realice algo parecido pero el pac me lo esta rebotando, agregue esta anotación
`@XmlSeeAlso({Nomina.class, Pagos.class})`
directamente en
mx.bigdata.sat.cfdi.v33.schema.Comprobante.java

**Comment by mega82es** [comment]
@camarillo unicamente agregue un test para generar el xml, sin validar, aun no hago pruebas de timbrado, en cuanto llegue a esa parte con gusto les comparto el status

que error te regresa el PAC?

**Comment by hortegag91** [comment]
Les aviso que acabo de hacer un push donde este error queda corregido!!

**Comment by camarillo** [comment]
@mega82es creo que era un error mio con el calculo de los impuestos. Con la corrección de @hortegag91 ya pasaron los documentos.

Gracias a ambos.

**Comment by hortegag91** [comment]
@camarillo no era error de calculos, el problema fue que el SAT definió parte del mismo catálogo de CFDi para los pagos, y según el error, dice que no puedes usar el mismo tipo de dato.
Lo que tuve que hacer para poder buildear "al momento" fue mdificar el XSD de pagos, y agregar de nuevo los catálogos que requiere del CFDi con un nombre distinto.
Debido a esto, si llegase a cambiar el XSD de los tipos de datos del complemento pagos, habrá que volver a modificar el XSD para ponerlos de nuevo.

**Comment by camarillo** [comment]
@hortegag91 si, ya volvi a bajar todo tal cual esta en la rama33 y ya funciona.

Gracias
