### ISSUE TITLE
Como agrego SchemaLocation a Detallista?

### ISSUE THREAD

**Issue by dpacanins** [bigdata-mx/factura-electronica#195]
Hola a todos 

estoy desarrollando la version 3.3 de CFDI y me esta manejando el siguiente error cuando intento timbrar 

No hay SchemaLocation de detallista

como puedo agregar este SchemaLocation a detallista?, antes se agregaba en un metodo que recibia la url del CFDI y la variable del schema, en el metodo CFD.guardar();

saludos

**Comment by hortegag91** [comment]
Hola @dpacanins 
Actualmente ya hay una versión de la versión 3.3 solo que se encuentra en un branch distinto.
Te recomiendo usarla para evitarte el trabajo de reimplementarlo.
Saludos.

**Comment by dpacanins** [comment]
Ok, gracias @hortegag91  por el dato

saludos

**Comment by dpacanins** [comment]
@hortegag91 tendras la url de esta version 3.3 que me la pases?

**Comment by dpacanins** [comment]
Hola @hortegag91  tendras el dato del branch que mencionas de la version3.3, lo he buscado y no lo encuentro

saludos

**Comment by dpacanins** [comment]
@hortegag91  ya encontre en donde

**Comment by dpacanins** [comment]
@hortegag91  ya encontre en donde, saludos
