### ISSUE TITLE
Recuperar complemento de Pagos

### ISSUE THREAD

**Issue by juanfra0064** [bigdata-mx/factura-electronica#202]
Alguien sabe como recuperar el complemento de pagos, pues al tratar de recuperarlo el tipo de elemento es un ElementNIImpl y no es posible recuperar el Objeto "Pagos" originalmente agregado.

**Comment by hortegag91** [comment]
En teoría desde este repo, todo debería funcionar correctamente.
https://github.com/GrupoCorasa/factura-electronica
