### ISSUE TITLE
Propiedad standalone=yes en documentos XML generados

### ISSUE THREAD

**Issue by elmer-garduno** [bigdata-mx/factura-electronica#30]
_Original author: victor.t...@gmail.com (January 09, 2011 07:12:57)_

<b>¿Cuáles pasos hay que seguir para reproducir el problema?</b>
<b>1.</b>
<b>2.</b>
<b>3.</b>

<b>¿Cuál es el resultado esperado? ¿Qué resulta en su lugar?</b>
ESPERADO
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;

RESULTA
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;

<b>¿Cuál versión del producto está utilizando?</b>
cfdi-base-0.1.5.jar

<b>Agregue cualquier información adicional que resulte de utilidad.</b>

Asi lo resolvi para CFDv2, no he usado CFDv3, pero si es de utilidad, anexo el fragmento.

package mx.bigdata.sat.cfd;
CFDv2.java

//Declaro el encabezado esperado
private static String XML_HEADER = &quot;&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&quot;;

  public void guardar(OutputStream out) throws Exception {
    Marshaller m = CONTEXT.createMarshaller();
    //Remuevo el encabezado
    m.setProperty(Marshaller.JAXB_FRAGMENT, Boolean.TRUE);
    ...
    //Genero el encabezado esperado y lo agrego al OutputStream 
    byte[] xmlHeaderBytes = getXMLHeaderByteArray(XML_HEADER);
    out.write(xmlHeaderBytes, 0, xmlHeaderBytes.length); 
    m.marshal(document, out);
  }
  //Se genera el byteArray a partir del encabezado esperado
  private byte[] getXMLHeaderByteArray(String xmlHeader) {
      char[] chars = xmlHeader.toCharArray();
      byte[] bytes = new byte[chars.length];
      for (int i = 0; i &lt; chars.length; i++) {
  bytes[i] = (byte)chars[i];
      }
      return bytes;

_Original issue: http://code.google.com/p/factura-electronica/issues/detail?id=30_

**Comment by x99mosealaaverga** [comment]
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
<long name="t2" value="1725497405701" />
<string name="K_1171477665">9201329C1890C2667FB71FACED3C3CB92E6D61700B78A7B70F3F339A17EFB6F6</string>
</map>
