### ISSUE TITLE
Nuevos certificados de prueba

### ISSUE THREAD

**Issue by painapol** [bigdata-mx/factura-electronica#73]
Que tal buenos dias, mi pregunta es si pudieran subir nuevos ejemplos para hacer pruebas, ya que los que estan dicen que expiraron el Sun Jul 29 10:58:41 GMT-06:00 2012.

De antemano muchas gracias

**Comment by hortegag91** [comment]
Hace ya un par de commits que se actualizaron los certificados, deben funcionar correctamente aunque no tardan mucho en caducar estos tambien. Cerraré el hilo. Saludos.
