### ISSUE TITLE
No se incluye la información del complemento Nómina en la cadena original

### ISSUE THREAD

**Issue by DanielMontesDeOca** [bigdata-mx/factura-electronica#98]
Hola a todos,

Espero que me puedan ayudar a encontrar el error y de ser un problema con la librería poder contribuir a corregirlo.

Tengo el siguiente código para el complemento Nómina:

``` java
mx.bigdata.sat.common.nomina.schema.ObjectFactory factoryNomina =  new mx.bigdata.sat.common.nomina.schema.ObjectFactory();
mx.bigdata.sat.common.nomina.schema.Nomina n = factoryNomina.createNomina();

                n.setVersion("1.1");
                n.setRegistroPatronal(configGeneral.getRegistroPatronalEmisor());
                n.setNumEmpleado("123");
                n.setCURP("MECC020123HDFNRR04");
                n.setTipoRegimen(Integer.parseInt("1"));
                n.setNumSeguridadSocial("SeguroSocial"); n.setRiesgoPuesto(Integer.parseInt(Nomina.catalogoRiesgoPuesto.get(configGeneral.getRiesgoPuestoEmisor())));

                mx.bigdata.sat.common.nomina.schema.Nomina.Percepciones p = factoryNomina.createNominaPercepciones();
                mx.bigdata.sat.common.nomina.schema.Nomina.Percepciones.Percepcion per = factoryNomina.createNominaPercepcionesPercepcion();
                per.setTipoPercepcion("001");
                per.setClave("Percepcion1");
                per.setConcepto("ConceptoPercepcion1");
                per.setImporteGravado(new BigDecimal("15"));
                per.setImporteExento(new BigDecimal("25"));
                p.getPercepcion().add(per);
                p.setTotalExento(BigDecimal.ZERO);
                p.setTotalGravado(BigDecimal.ZERO);
                n.setPercepciones(p);

.               //Resto de los campos de la nomina

            mx.bigdata.sat.common.implocal.schema.ImpuestosLocales im = new mx.bigdata.sat.common.implocal.schema.ObjectFactory().createImpuestosLocales();
            im.setTotaldeRetenciones(BigDecimal.ZERO);
            im.setTotaldeTraslados(BigDecimal.ZERO);
            im.setVersion("1.0");

mx.bigdata.sat.cfdi.v32.schema.Comprobante.Complemento com = factory.createComprobanteComplemento();
com.getAny().add(n);
com.getAny().add(im);
c.setComplemento(com);

CFDv32 cfd = new CFDv32(c, "mx.bigdata.sat.common.nomina.schema", "mx.bigdata.sat.common.implocal.schema");
cfd.addNamespace("http://www.sat.gob.mx/nomina", "nomina");
cfd.addNamespace("http://www.sat.gob.mx/implocal", "implocal");

cfd.sellarComprobante(key,certificado); // Firma el CFD y obtiene un Comprobante sellado

cfd.validar(); 
cfd.verificar();
```

El xml se genera bien en cuanto a estructura, todo aparece en su lugar como debe ser. El problema es al validarlo, me marca el siguiente error:

The matching wildcard is strict, but no declaration can be found for element 'ns3:Nomina'.]

Y al revisar la cadena original generada esta incluye los campos del cfdi y del complemento impuestosLocales pero no del complemento Nomina. Si genero el cfdi solamente con el complemento impuestosLocales por ejemplo, se valida correctamente.

Ya intenté actualizando los archivos y recompilando la librería sin éxito, ya revisé hasta donde pude el código y no veo nada fuera de lugar, comprobé que todas las rutas están bien pero al parecer en el momento de ejecución por alguna razón no se reconoce el nodo Nomina como el complemento Nómina.

¿Alguien sabe a que se puede deber esto?

Gracias de antemano.

**Comment by JJAMBurgos** [comment]
Para el que le sirva esto se corrige cambiando el método guardar() en la clase CFDv32 de la siguiente forma:

  public void guardar(OutputStream out) throws Exception {
    Marshaller m = context.createMarshaller();
    m.setProperty("com.sun.xml.bind.namespacePrefixMapper",
                  new NamespacePrefixMapperImpl(localPrefixes));
    m.setProperty(Marshaller.JAXB_FRAGMENT, Boolean.TRUE);
    m.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
    m.setProperty(Marshaller.JAXB_SCHEMA_LOCATION, 
                  "http://www.sat.gob.mx/cfd/3  " + 
                  "http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd " +
                  "http://www.sat.gob.mx/nomina12 " +
                  "http://www.sat.gob.mx/sitio_internet/cfd/nomina/nomina12.xsd");
    byte[] xmlHeaderBytes = XML_HEADER.getBytes("UTF8");
    out.write(xmlHeaderBytes); 
    m.marshal(document, out);
  }

Saludos
